name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Lint
      run: make lint

    - name: Formatting
      run: make format

    - name: Tests
      run: make test

